# Generated by Django 3.2 on 2021-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255)),
                ('material_name', models.CharField(max_length=255)),
                ('mass', models.IntegerField()),
                ('is_recycled', models.BooleanField()),
            ],
        ),
    ]
