# Generated by Django 3.2 on 2021-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('test2', 'Test2')], default='Undefined', max_length=255),
            preserve_default=False,
        ),
    ]
