# Generated by Django 3.0 on 2021-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Others', 'Others'), ('Household products', 'Household products'), ('Food products', 'Food products')], max_length=255),
        ),
    ]
