# Generated by Django 3.2 on 2021-04-16 11:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=django_countries.fields.CountryField(default='fr', max_length=2),
            preserve_default=False,
        ),
    ]
